### ISSUE TITLE
После добавление второго аккаунта приложение продолжает использовать первый

### ISSUE THREAD

**Issue by bogolt** [GoodKitties/Fair#1]
Добавил второй аккаунт, успешно залогинился. В приложении поменялся мой никнейм и название дневника, но на страницах моего дневника - остался старый аккаунт. Удалил основной, оставил только новый - ничего не изменилось.

**Comment by simoroshka** [comment]
новый аккаунт или профиль? У меня нет проблем со вторым аккаунтом.

2018-09-24 10:52 GMT+03:00 Dmitriy Seniy <notifications@github.com>:

**Comment by bogolt** [comment]
Именно аккаунт ( на другой почте ).

**Comment by bogolt** [comment]
@simoroshka но это же не веб приложение, так что это в любом случае не твой баг =)

**Comment by simoroshka** [comment]
Потому что ты небось его в базе просто добавил, а не сделал инвайт.
Создавал профиль и блог?

**Comment by bogolt** [comment]
не не, я все сделал по-честному. Пригласил другой своей емейл,  создал его сайт. все окейно работало. Потом добавил второй акк в приложение ( там можно больше одного добавлять) и вот тут начались эти странности.

**Comment by simoroshka** [comment]
А. Точняк)

**Comment by simoroshka** [comment]
Как хорошо, когда баги не твои)))

**Comment by Adonai** [comment]
Acknowledged

**Comment by Adonai** [comment]
AcknowledgedFixed in latest master, wait for release
