### ISSUE TITLE
Таблицы

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#10]
![screenshot_2018-12-17-16-14-17-885_com kanedias dybr fair](https://user-images.githubusercontent.com/33664001/50089473-fab1c080-0216-11e9-9ec6-c0f7bbecc3e3.png)
![screenshot_2018-12-17-16-14-07-030_com opera browser](https://user-images.githubusercontent.com/33664001/50089483-03a29200-0217-11e9-9044-bd8595a3f886.png)

**Comment by Herbst2017** [comment]
https://dybr.ru/blog/vezuvian/3320?page=1#

**Comment by Adonai** [comment]
Да, с таблицами всё плохо сейчас.
Буду смотреть позже, когда с остальным разберусь.

**Comment by Adonai** [comment]
Исправлено

<details><summary>Картинка под катом</summary>
![image](https://user-images.githubusercontent.com/863272/82733608-6ea5a180-9d04-11ea-8962-bec10bae47a1.png)
</details>
