### ISSUE TITLE
Высота/ширина при загрузке изображения

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#14]
При загрузке предлагается выбрать высоту картинки. В коде проставляется это значение в ширину.
Можно, оставить будет в итоге высоту auto?

![screenshot_2019-01-15-10-45-10-576_com kanedias dybr fair](https://user-images.githubusercontent.com/33664001/51165995-288c3280-18b3-11e9-93a2-268555364755.png)
![screenshot_2019-01-15-10-45-19-225_com kanedias dybr fair](https://user-images.githubusercontent.com/33664001/51166023-393ca880-18b3-11e9-8686-d90a26e9b6f0.png)

**Comment by Adonai** [comment]
Исправлю на "ширину"

**Comment by Adonai** [comment]
Перепроверить.

**Comment by Herbst2017** [comment]
есть новая версия?
сейчас приложение вылетает при попытке загрузить картинку.

**Comment by Adonai** [comment]
@Herbst2017, сегодня будет.

**Comment by Adonai** [comment]
Исправил, наконец-то. См. https://github.com/GoodKitties/Fair/commit/588229a224e40d4e859cd7b41242045e21cd3775
