### ISSUE TITLE
Замена - на * (Markdown vs. Plain text)

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#17]
При публикации в оформлении диалога значок "-" заменился на "*", в посте выглядит как маркированный список с жирными точками. Редактирование * на - игнорируется.

**Comment by Herbst2017** [comment]
Почитала про markdown. Видимо, это особенность разметки. 
Может можно как-то обойти?

**Comment by Herbst2017** [comment]
А вообще есть возможность в приложении делать записи, не оглядываясь на markdown? Мешает автоматически проставляется тег <p>

**Comment by Adonai** [comment]
Публикуйте с эскейпингом, вместо "-" ставьте "\\-"

> А вообще есть возможность в приложении делать записи, не оглядываясь на markdown?

Записи на ресурсе dybr.ru это HTML. Если обычный текст просто отправить без преобразования в HTML, он потеряет все двойные пробелы, переносы строк и знаки < >. Поэтому и используется Markdown, т.к. он как раз и предназначен для преобразования в HTML.

Пока некритично. Я думаю, есть способ автоматически перевести обычный текст в HTML.
Пусть баг остаётся открытым, если кому-то захочется реализовать эту возможность, буду раз патчам.

**Comment by Kaned1as** [comment]
Перенесено в [GitLab](https://gitlab.com/dybr-ru/Fair/-/issues), подпишитесь там, для уведомлений. Этот репозиторий архивирован.
