### ISSUE TITLE
Нет доступа к кнопкам комментирования и удаления

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#18]
При комментировании кнопка добавления нового комментарии перекрывает кнопки удаления и редактирования.
![Screenshot_2019-03-22-12-55-45-752_com kanedias dybr fair](https://user-images.githubusercontent.com/33664001/54815110-43f42f00-4ca2-11e9-84ec-185ad3a37365.png)

**Comment by Adonai** [comment]
А теперь?

**Comment by Herbst2017** [comment]
А теперь не могу зайти в аккаунт в приложении

**Comment by Adonai** [comment]
Слишком мало информации

**Comment by Adonai** [comment]
@Herbst2017 , статус этой задачи?

**Comment by Herbst2017** [comment]
А что изменилось? 

Сейчас я нашла тот самый пост, но тогда мой коммент был единственным, и вместе с постом они занимали весь экран без возможности прокрутки. Сейчас там несколько чужих комментов, ленту можно покрутить и легко поймать момент, когда кнопки редактирования/удаления не перекрываются плюсиком. 

Если изменения в возможности прокрутить немного вверх поле, то можем закрывать обращение.

**Comment by Adonai** [comment]
> Если изменения в возможности прокрутить немного вверх поле, то можем закрывать обращение.

Да, теперь можно чуть выше прокрутить, даже если один коммент. Надеюсь, этого будет достаточно.
