### ISSUE TITLE
Отображение неработающих тегов

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#19]
Во всех записях одного юзера в приложении вижу неработающие html-теги, центрирование и выделение жирным, парные.
![IMG_20190412_111326](https://user-images.githubusercontent.com/33664001/56022838-408a1b80-5d15-11e9-88e6-e854f1833c1e.jpg)
![Screenshot_2019-04-12-11-17-45-387_com opera browser](https://user-images.githubusercontent.com/33664001/56022857-4c75dd80-5d15-11e9-8818-83cd42aa725e.png)

**Comment by Adonai** [comment]
@Herbst2017 создавайте баги по шаблону, пожалуйста.

**Comment by Adonai** [comment]
Посмотрел.

Это баг сайта. Сайт тоже должен показывать эти тэги. В контенте поста они есть, причём заэскейпленные правильным образом, чтобы не превращаться в html-контент, а отображаться исключительно как текст. Почему этого не происходит - не знаю. Спрошу у ответственных людей.
