### ISSUE TITLE
изображения в посте загружаются сразу и перекрывают текст

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#2]
Просмотр из вкладки "мой дневник".
Изображения, которые раньше отображались кодом (из-за пробела в имени), теперь отображаются сразу при загрузке страницы (а не иконкой OBJ) и при этом перекрывают текст, который находится в посте выше.
![screenshot_2018-10-28-13-03-25-568_com kanedias dybr fair](https://user-images.githubusercontent.com/37691742/47614689-c5111680-dab4-11e8-82b8-886221357674.png)
После обновления страницы отображается нормально.
![screenshot_2018-10-28-13-07-31-201_com kanedias dybr fair](https://user-images.githubusercontent.com/37691742/47614694-ce9a7e80-dab4-11e8-8e0f-d9d99ddd64a7.png)

**Comment by Adonai** [comment]
Работаю над этим, но пока просветов нет. Судя по всему, такая проблема у многих приложений, где есть изображения в текстовых полях.

**Comment by Adonai** [comment]
Обновиться и перепроверить

**Comment by Adonai** [comment]
Нет ответа от автора.
