### ISSUE TITLE
Не отображаются записи старее 15.04.2019 при поиске по тэгам

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#20]
**Описание бага и как повторить**
Не отображаются записи раньше 15 апреля 2019, если просматривать по тэгам. Проверено в своём дневнике и по некоторым из избранного.

Шаги для появления бага в приложении:
1. Зайти в любой дневник, в котором есть записи старее 15.04.2019 с проставленными тэгами
2. Перейти по тэгу
3. Пролистать вниз и увидеть, что старые записи не отображаются

**Ожидаемое поведение**
Должны отображаться все записи дневника с одним и тем же тэгом

**Моё окружение:**
Android 7.1.2
Xiaomi Mi 5X
Fair 1.13.8 (64)

**Дополнительная информация (если применимо)**
Можно потестить по [моему дневнику](https://dybr.ru/blog/panderoma), там тэги поставлены по самое начало (март 2018). Ещё подгружен архив из дайри (тоже с тэгами), но он закрыт.

**Comment by Adonai** [comment]
Отправил на рассмотрение @bogolt

**Comment by Adonai** [comment]
@bogolt, есть прогресс?

**Comment by PandeRoma** [comment]
УПД:
теперь по тэгам не отображаются записи старее начала июня 2019.

**Comment by bogolt** [comment]
там ползущая дата, не больше чем год назад. Пока исправить не удалось

**Comment by bogolt** [comment]
Пофиксил на проде. Теперь нормално скроллит по тегу до 2018 года, та же запись что винда на сайте. @PandeRoma спасибо еще раз =)
