### ISSUE TITLE
Увеличение счётчика реакций на 2 при двойном щелчке

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#21]
**Описание бага и как повторить**

Шаги для появления бага в приложении:
1. Найти запись с уже проставленной реакцией
2. Сделать двойной щелчок по реакции

**Ожидаемое поведение**
Увеличение счётчика реакций на 1 даже при двойном щелчке, либо
Одновременное добавление и удаление реакции, т.е. нулевой результат, потому что нечего шататься везде и нажимать куда попало по два раза.

**Comment by Adonai** [comment]
Хммм а мненравится, можно накручивать себе реакции ))

**Comment by Adonai** [comment]
Ладно, понял, это мой косяк, поправлю.

**Comment by Adonai** [comment]
Исправлено в 954e2f4fd0cf51ad4ec5d23a22e5e769ee33be26
