### ISSUE TITLE
При открытии MORE страница прокручивается вверх к началу записи

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#22]
**Описание бага и как повторить**
Шаги для появления бага в приложении:
1. Найти запись с частью текста, скрытым под MORE.
2. Открыть MORE.
3. Удивиться, что страница уехала наверх и теперь придётся прокручивать вниз и искать, с какого места продолжать читать.

**Ожидаемое поведение**
При открытии MORE страница не будет прокручиваться никуда.

**Comment by Adonai** [comment]
будет в релизе 1.14.1

**Comment by PandeRoma** [comment]
> будет в релизе 1.14.1

У меня сейчас 1.14.1 - первое море в записи открывается нормально, со второго и далее страница всё равно уезжает к началу поста.

**Comment by Adonai** [comment]
Посмотрю на днях.

**Comment by Adonai** [comment]
Исправлено?

**Comment by PandeRoma** [comment]
Да, спасибо.
Но.
На открытии седьмого(?) моря, все предыдущие открытые закрываются, и ты оказываешься глубоко внизу страницы совершенно на другом посте. Это если из избранного или дневника автора смотреть.
Если смотреть через страницу отдельной записи, то начинает прокручивать наверх до какого-то странного места.
Проверяю по этой записи: https://dybr.ru/blog/natoth/396869 в ней много морей и много картинок. Может быть, в них причина. (пока тестила - приложение рухнуло. Видимо, из-за картинок...)

**Comment by Adonai** [comment]
Посмотрю, что там. Если не затруднит, создайте из этого коммента новый баг, у меня память как у золотой рыбки.
