### ISSUE TITLE
Приложение падает при двойном щелчке рядом с картинкой

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#23]
**Описание бага и как повторить**
Шаги для появления бага в приложении:
1. два раза щёлкнуть в пустую область правее изображения в записи

**Ожидаемое поведение**
Да пусть хотя бы ничего не происходит. Или пусть картинка открывается.

**Дополнительная информация (если применимо)**
Триггерится не каждый раз. Подозреваю, что зависит от места двойного щелчка.
Краш-репорты посылала. Могу ещё выслать, если надо.

**Comment by Adonai** [comment]
Сейчас воспроизводится?

**Comment by PandeRoma** [comment]
Воспроизводится. 
Версия 1.15.0 (70)

**Comment by Adonai** [comment]
Спасибо, посмотрю завтра.

**Comment by Adonai** [comment]
Давайте ссылку, где проще всего увидеть это поведение.

**Comment by PandeRoma** [comment]
Получается не всегда с первого раза. Иногда даже на какой-нибудь десятый. Вот тут более-менее удобно тыкать правее картинки: https://dybr.ru/blog/tsumi/1657440
Могу ещё раз отравить отчёт об ошибке, если есть необходимость. Могу попробовать записать видео, если от этого может стать понятней.

**Comment by Kaned1as** [comment]
Перенесено в [GitLab](https://gitlab.com/dybr-ru/Fair/-/issues), подпишитесь там, для уведомлений. Этот репозиторий архивирован.
