### ISSUE TITLE
Страница ведёт себя странно при открытии нескольких морей с картинками

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#24]
**Описание бага и как повторить**
После открытия моря с большим количеством картинок, загруженных не на дыбросервер, а вставленных с других ресурсов, и дальнейшего открытия других морей в записи страница начинает вести себя странно: 
- если просматривать запись через избранное или дневник, то страница уезжает вниз. Иногда при этом все открытые моря закрываются. 
- если просматривать через страницу записи - страница уезжает вверх.

Шаги для появления бага в приложении:
1. Найти запись с большим количеством картинок в море, после которого есть ещё моря.
2. Раскрыть море с картинками.
3. Раскрыть последующее море.

**Ожидаемое поведение**
Страница не буде прокручиваться ни вверх, ни вниз.

**Дополнительная информация (если применимо)**
Вот тут сделала иллюстрирующую запись, можно потыкать и посмотреть, что я имею в виду: https://dybr.ru/blog/panderoma/1446621
Поэкспериментировала немного:
- картинки с дыбросервера в принципе не загружаются автоматически, поэтому с ними всё в порядке.
- пробовала добавлять в каждое море по одной картинке большого размера (1-2,8 МБ), получалось, что от размера поведение страницы не зависит, зависит от количества.

**Comment by Kaned1as** [comment]
Перенесено в [GitLab](https://gitlab.com/dybr-ru/Fair/-/issues), подпишитесь там, для уведомлений. Этот репозиторий архивирован.
