### ISSUE TITLE
текст offtop никак не выделен

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#25]
**Описание бага и как повторить**
Текст, оформленный, как offtop, в приложении выглядит как обычный текст. 

**Ожидаемое поведение**
Текст offtop имеет цвет, определённый в дизайне.

**Comment by Adonai** [comment]
Попробую поправить на след. выходных

**Comment by Adonai** [comment]
Сложнее, чем думал. Фикс задерживается.
