### ISSUE TITLE
Некорректно отображается MORE, помещённое в другое MORE

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#26]
**Описание бага и как повторить**
Некорректно отображается MORE, помещённое в другое MORE. (В браузере отображается правильно).

Запись формата:
`внешний текст 1
<br>[MORE=внешнее море] внутренний текст 1
<br> [MORE=внутреннее море]содержание внутреннего моря[/MORE]
<br> внутренний текст 2[/MORE]
<br> внешний текст 2`
выглядит:
![image](https://user-images.githubusercontent.com/37691742/74106272-56a37b00-4b76-11ea-8870-21ef8a8a800a.png)

**Comment by Adonai** [comment]
Будет исправлено в версии 1.16.0
