### ISSUE TITLE
Значок уведомления о новых комментариях не исчезает

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#27]
**Описание бага и как повторить**
Значок уведомления о новых комментариях не исчезает при прочтении комментария через браузер. Не исчезает вообще никак, даже если перейти по нему на страницу оповещений в приложении и открыть комментарий.

Шаги для появления бага в приложении:
1. Дождаться комментария в дневнике или дискуссии
2. Прочитать новый комментарий через браузер

**Ожидаемое поведение**
Значок будет исчезать, когда комментарий прочитан, не важно каким образом. 

**Моё окружение:**
Android 7.1.2
Xiaomi Mi 5X
Fair 1.14.3 (69)

**Comment by Adonai** [comment]
Перепроверить

**Comment by PandeRoma** [comment]
1.16.1 (72)
Нет. 
Комментарий на странице уведомлений значится, как прочитанный, но значок висит. 
Висит даже по прошествии 15 минут, установленных как частота проверки уведомлений.
Исчезает, только если перейти в приложении на страницу записи (или перещёлкать галочку о прочтении). 

немного оффтоп:
иногда выскакивает один значок: "у вас новый комментарий" (ссылается на страницу уведомлений) - иногда два значка: "у вас новый комментарий" и второй с началом текста комментария, который ссылается на страницу записи. Если с момента последней проверки получено больше 1 комментария - то два значка (Может быть и больше бывает. Не уверена). Если получен один комментарий - то по-разному: то один, то два.
Так вот если удалить запись, на которую ссылается значок, ссылающийся на эту запись, и перейти по значку, то высвечивается ошибка no_user и значок опять же никуда не пропадает.

совсем оффтоп:
нельзя ли сделать частоту проверки 30 секунд, как в браузере? В идеале, конечно, моментально, как в вк или телеге.

**Comment by Adonai** [comment]
Ок, посмотрю.

> нельзя ли сделать частоту проверки 30 секунд, как в браузере?
Батарейка сядет моментально.

**Comment by Adonai** [comment]
В 1.16.2 через 15 минут должны пропадать, если были прочитаны где-то ещё или удалены.
Просьба перепроверить.

**Comment by PandeRoma** [comment]
Проверено. Через 15 минут пропадает.

В качестве предложения: было бы здорово, если бы значок о новых комментариях (если они уже прочитаны) исчезал при переходе на страницу уведомлений. Как я понимаю, в этот момент всё равно отправляется запрос на сервер о состоянии прочитанности комментариев. Если новых нет - сбрасывать значок. (Звучит несложно, но кто его знает, может, для этого нужно новых велосипед придумать. Поэтому на усмотрение).

**Comment by Adonai** [comment]
Звучит удобно. Сделаю, спасибо.
