### ISSUE TITLE
Многократная отправка записи

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#28]
**Описание бага и как повторить**
При нестабильном интернет-соединении запись не отправляется сразу и есть возможность нажать несколько раз на кнопку "отправить". При восстановлении соединения запись публикуется несколько раз.

Шаги для появления бага в приложении:
1. Попасть в зону плохого сигнала (залезть в бункер, сесть в вагон метро...)
2. Создать запись, нажать на кнопку "отправить" несколько раз.
3. Выйти из бункера до того, как приложение оповестит об ошибке соединения.
4. Увидеть у себя в дневнике несколько одинаковых записей.

**Ожидаемое поведение**
После однократного нажатия кнопка "отправить" будет блокироваться (и разблокироваться, когда приложение решит, что отправить не удалось). А то возникают сомнения: может, я плохо нажимаю?

**Comment by Adonai** [comment]
Будет в версии 1.16.0
