### ISSUE TITLE
Приложение падает при загрузке изображения 

### ISSUE THREAD

**Issue by Zimorodka** [GoodKitties/Fair#29]
**Описание бага и как повторить**
Чёткое и понятное объяснение того, в чём проявляется баг.
Шаги для появления бага в приложении:
1. Зайти в избранное. 
2. Нажать на изображение, чтобы оно появилось в полном размере. 
3. Нажать значок сохранения внизу. 

**Ожидаемое поведение**
Сохранение изображения. 

**Моё окружение:** 
 - Версия Android - 10, Miui 11.
 - Модель телефона - Xiaomi MI 8 pro
 - Версия приложения - 1.15.0 - 10-ge6da988.

**Comment by Adonai** [comment]
Посмотрю на выходных

**Comment by Adonai** [comment]
Исправлено в версии 1.16.1
