### ISSUE TITLE
При обновлении страница прокручивается вниз 

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#3]
При обновлении страницы своего дневника (слайд пальцем вниз сверху страницы), страница самопроизвольно прокручивается вниз (не рандомно, в определённое место N1). 
Если сделать новую запись, обновляется нормально. Т.е. скроллинг остаётся в самом верху страницы. Если удалить запись - иногда опять прокручивается вниз, но уже к другому месту N2.
Если выйти из приложения и снова зайти - опять при обновлении прокручивается к месту N1.
При обновлении страницы через кнопку меню Refresh обновляется нормально, т.е. скроллинг остаётся на том месте, где был до обновления.

**Comment by Adonai** [comment]
Посмотрю на этой неделе

**Comment by Adonai** [comment]
После выходных перепроверить.

**Comment by Adonai** [comment]
Нет ответа от автора.
