### ISSUE TITLE
 Нерелевантные подсказки для второго и далее тэгов

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#30]
**Описание бага и как повторить**
При добавлении второго и далее тэга в записи, в списке предлагаемых тэгов всплывают сильно левые (у которых введённая буква далеко не на первом месте).
То же самое происходит, если добавить тэг, стереть, и начать вводить снова.

Шаги для появления бага в приложении:
1. На странице новой записи добавить в запись тэг.
2. Попробовать добавить ещё один тэг.

**Ожидаемое поведение**
Будет автоматически проставляться # и для второго и далее тэгов.

**Comment by Adonai** [comment]
Исправлено в 1.16.2

**Comment by PandeRoma** [comment]
Вообще трэшняк какой-то начался, если честно. Теперь и первый тэг подбирается не по первому слову.
То есть, если хочешь вбить тэг "пришла весна", нужно начинать набирать не "при", а "ве". =/

**Comment by Adonai** [comment]
@PandeRoma можете скринкаст записать? Не могу воспроизвести.

**Comment by PandeRoma** [comment]
Там ещё каждый раз при открытии-закрытии приложения список тэгов в всплывающей подсказке шафлиться в какой-то странный порядок, и не по алфавиту, и не по частоте использования. Каждый раз по-разному. Не то чтобы это была проблема, просто непонятна логика.

Видео. В нём видно, что тэги подбираются не по первому слову.
[20200322_234458.zip](https://github.com/GoodKitties/Fair/files/4366332/20200322_234458.zip)

**Comment by Adonai** [comment]
Спасибо большое за видео, понял проблему. Здесь поиск работает по подстроке, а не по первому слову. 

Я понимаю ваш юзкейс, когда нужно сильно срезать количество вариантов изначально, но всё же считаю, что лучше оставить сейчас как есть.

Люди, у которых длинные тэги из целого предложения, часто помнят только последние их слова, например "что-то-там ещё-что-то брайан молко". И с таким способом поиска они смогут их отыскать.

Могу сделать так, чтобы первыми в списке были тэги, которые начинаются с введённых букв, а ниже уже поиск по подстроке. Что скажете?

**Comment by PandeRoma** [comment]
Я совсем не против, что тэги подбираются по всем словам. Пусть будет, это реально удобно. Но. У меня (может быть только у меня?) тэги подбираются по всем словам, кроме первого. 
Например, при вводе словосочетания "кни" - в списке появляется всё, что угодно, кроме подсказки на тэг "книжки". В принципе, не проблема самому дописать слово "книжки", но вот есть у меня тэг "АААА!!!", и я каждый раз не помню, сколько там "А" и сколько там "!". 
То есть, моя проблема в том, что я начинаю вводить (длинный) тэг с первого слова - а в подсказках есть всё, кроме того, что я начинаю вводить.
Среди моих тэгов, например, нет ни одного, у которого вторые и далее слова начинаются с "а", поэтому при попытке подобрать пресловутое "АААА!!!" в подсказках пустота.
П.С.
По первому слову начинает подбираться, если начать печатать с символа решётки. Т.е. решётку поиск считает частью слова (?). Но это же муторно каждый раз её впечатывать. Т_Т Тем более, что интуитивно кажется, что приложение само решётку должно подставить и без меня.
