### ISSUE TITLE
Изображение не подгружается, если оно заменяет "читать дальше" в MORE

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/Fair#31]
**Описание бага и как повторить**
Если в качестве замещающего текста в тэге MORE использовать изображение, то оно не подгружается при просмотре записи, вместо него отображается значок OBJ.
При щелчке на объект открывается море, т.е. изображение, использованное в качестве превью, не увидеть никаким способом (если только в записи нет других изображений, которые можно пролистать влево-вправо).

Шаги для появления бага в приложении:
1. Создать запись с тэгом MORE, заменить замещающий текст ссылкой на изображение.

**Ожидаемое поведение**
Изображение будет подгружаться (в настройках стоит галочка автоматической загрузки изображений).

**Скриншоты**

![image](https://user-images.githubusercontent.com/37691742/77862863-e4225380-7226-11ea-92fb-4a008e75c59d.png)

**Дополнительная информация (если применимо)**
Косит только с морем. Если делать изображение ссылкой `<a></a>`, то подгружается нормально.

**Comment by Kaned1as** [comment]
Перенесено в [GitLab](https://gitlab.com/dybr-ru/Fair/-/issues), подпишитесь там, для уведомлений. Этот репозиторий архивирован.
