### ISSUE TITLE
Обновление ленты после скрытия юзера

### ISSUE THREAD

**Issue by PhoenixMonster** [GoodKitties/Fair#32]
Когда читаю общую ленту, и на каком-то моменте хочется убрать кого-то из нее, я вынуждена этого не делать, потому что знаю, что после нажатия нужной кнопки лента обновится, и я вернусь в начало, к самым свежим постам.

Хочется иметь настройку, которая выключает обновление ленты после скрытия пользователя из ленты, чтобы не терять то место, где сейчас ее читаешь - пусть даже неугодные посты все еще будут показываться до первого мануального обновления страницы.

Спасибо!

**Comment by Adonai** [comment]
Исправлено в версии 1.16.8, ждите обновления
