### ISSUE TITLE
Редактор

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#6]
При нажатии кнопки цитирования курсор встаёт слева от скобки. Набранный/вставленный текст тогда не воспринимается цитатой.

Не баг, но вопрос:
В чем назначение кноки <...>? В приложении заключённый между скобок текст выделяется. В браузере нет.

**Comment by Adonai** [comment]
Исправлено, релиз будет на выходных.

**Comment by Adonai** [comment]
> В чем назначение кноки <...>?

Это "код". Там применяется моноширинный шрифт. CSS у сайта пока нет, поэтому там не видно.
