### ISSUE TITLE
Лишний символ в текстах

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#7]
При оформлении диалогов в текстах отображается лишний обратный слэш.
![screenshot_2018-12-13-16-29-01-440_com kanedias dybr fair](https://user-images.githubusercontent.com/33664001/49941817-a34ce100-fef4-11e8-8e79-b919fc7cd6e7.png)
![screenshot_2018-12-13-16-28-50-544_com opera browser](https://user-images.githubusercontent.com/33664001/49941831-ac3db280-fef4-11e8-9830-39be00b90605.png)

https://dybr.ru/blog/juu/2972?page=1#

**Comment by Adonai** [comment]
Уже должно быть исправлено в последнем обновлении, просьба перепроверить.

**Comment by Herbst2017** [comment]
Да, сейчас лишних символов нет
