### ISSUE TITLE
Конец цитаты

### ISSUE THREAD

**Issue by Herbst2017** [GoodKitties/Fair#8]
Не заканчивается цитирование. 
Ставлю цитату, через >.
Перехожу на новую строчку, пишу дальше текст. После публикации > проставляются для каждого абзаца. И весь набранный текст попадает в блок цитаты.

**Comment by Adonai** [comment]
Перепроверить

**Comment by Herbst2017** [comment]
Обновилась. Все по прежнему.
Одиночное нажатие enter добавляет текст в блок цитаты. Двойное уже нет.

**Comment by Adonai** [comment]
Я неправильно понял баг. Перепроверю.

**Comment by Adonai** [comment]
Похоже, это поведение корректное. Markdown так и работает. Здесь же, на гитхабе и проверил.

![image](https://user-images.githubusercontent.com/863272/50190107-efef4c80-0338-11e9-9d0c-d94e063f044e.png)
![image](https://user-images.githubusercontent.com/863272/50190125-ff6e9580-0338-11e9-8cc5-eaf0b1320238.png)

**Comment by Herbst2017** [comment]
ок, то есть просто использовать двойной клик по Enter для "выхода" из цитаты. И одинарный для перехода на новую строку внутри цитаты. 
сложнааа
