### ISSUE TITLE
Раздвоение комментариев

### ISSUE THREAD

**Issue by Zimorodka** [GoodKitties/Fair#9]
https://a.radikal.ru/a33/1812/cf/c4328f3aa668.png
Скрин по ссылке. Возможно, этот баг возник из-за глюкнувшего интернета, но кто знает.

**Comment by bogolt** [comment]
Ага спасибо, у меня так тоже раз случилось, на слабом почти умирающем интернете. Мы решили чуть притормозить с решением пока не наберем немного статистики по этому багу, так как до сих пор только один или два случая было. Если еще встретите пишите сюда.

**Comment by Adonai** [comment]
Баг бэкенда. 
@Zimorodka спасибо за репорт, это уйдёт во внутренный багтрекер.

Тут закрываю.
